// Known-answer tests for the PNG decoder. The fixtures were generated by
// an independent Python implementation of PNG filtering and Adam7
// interlacing (see the per-fixture comments for the pixel formulas) and
// every opaque fixture was pixel-verified against macOS ImageIO before
// being checked in; the only divergence is 16-bit reduction, where
// ImageIO rescales with rounding while we take the high byte (libpng
// strip-16 convention).
import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';

import 'package:archive/archive.dart';
import 'package:pdf_document/src/png.dart';
import 'package:test/test.dart';

// 4x5 RGB-8, one row per filter type (None/Sub/Up/Average/Paeth);
// pixel = (x*40, y*40, x*y*10+5)
const _rgbFilters =
    'iVBORw0KGgoAAAANSUhEUgAAAAQAAAAFCAIAAADtz9qMAAAAOElEQVR4nCWJqREAMQzElMfE'
    'eMkR4y0n5aT8JHMaEY2AMLGITTR8I387BicWrsEaenxSzXdIENQBkPAEKP0mt2sAAAAASUVO'
    'RK5CYII=';

// 2x2 RGBA-8: (255,0,0,255) (0,255,0,128) / (0,0,255,0) (10,20,30,77)
const _rgba =
    'iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAGUlEQVR4nGP4z8DwHwgbWBgZ'
    '/jNyicr7AgA3BAUOTnqjAAAAAABJRU5ErkJggg==';

// 3x2 gray-16: 0x00FF 0x80FF 0xFFFF / 0x1100 0x2280 0x33FF
const _gray16 =
    'iVBORw0KGgoAAAANSUhEUgAAAAMAAAACEAAAAADoj+WFAAAAFklEQVR4nGNg+N/w//9/JkHG'
    'RY0mDAAxUwXoUSw58gAAAABJRU5ErkJggg==';

// 4x2 palette-4bit, palette [red green blue], tRNS [255,128,0];
// indices 0,1,2,0 / 2,2,1,1
const _palette4 =
    'iVBORw0KGgoAAAANSUhEUgAAAAQAAAACBAMAAACNhmBQAAAACVBMVEX/AAAA/wAAAP8tSs2K'
    'AAAAA3RSTlP/gAB/bWh4AAAADklEQVR4nGNgVGBUeg8AAcEBNEMRhbgAAAAASUVORK5CYII=';

// 9x2 gray-1bit: rows 101010101 / 110011001 (packing crosses a byte)
const _gray1 =
    'iVBORw0KGgoAAAANSUhEUgAAAAkAAAACAQAAAACiLct+AAAADklEQVR4nGNY1cBwpgEAB3AC'
    'dzKBI80AAAAASUVORK5CYII=';

// 9x9 RGB-8 Adam7 interlaced, filters cycling inside each pass;
// pixel = (x*25, y*25, (x+y)*12)
const _interlaced =
    'iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJCAIAAAEY9KHRAAAAk0lEQVR4nG3MsQnDMBAF0C87'
    'pd2k8u81gLjClQcQqPUAKq5Mky6Nd3ClNbyGxsoZgyDB8ODg/7sDgIrsULMNKILTugMaVHPV'
    'HYKpIDrRaF1n+QkyiQSVWCRX+TiUaHsNiCHBb1gOrI7iW9PZZdOPOpPT5XFmaDhYJvSJQbls'
    'jIXrwVz5ckje/t/6ef+nx3se+bz1BWBGJ2onRAnuAAAAAElFTkSuQmCC';

// 2x2 gray+alpha-8: (10,255) (200,0) / (99,128) (0,1)
const _grayAlpha =
    'iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAQAAADYv8WvAAAAEklEQVR4nGPg+n+CgTmOMfsg'
    'ABD1A2C8E/7bAAAAAElFTkSuQmCC';

// 2x2 RGB-8 with color key (0,255,0): red, green / green, (9,9,9)
const _colorKey =
    'iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAABnRSTlMAAAD/AADQPjN8AAAA'
    'EUlEQVR4nGP4z8DAAMGcnJwAGykDGUbpjUkAAAAASUVORK5CYII=';

Uint8List _bytes(String b64) => base64.decode(b64);

void main() {
  test('RGB with every filter type', () {
    final png = PngImage.decode(_bytes(_rgbFilters));
    expect((png.width, png.height, png.components), (4, 5, 3));
    expect(png.alpha, isNull);
    for (var y = 0; y < 5; y++) {
      for (var x = 0; x < 4; x++) {
        final i = (y * 4 + x) * 3;
        expect(png.samples.sublist(i, i + 3), [x * 40, y * 40, x * y * 10 + 5],
            reason: 'pixel ($x,$y)');
      }
    }
  });

  test('RGBA splits the alpha channel', () {
    final png = PngImage.decode(_bytes(_rgba));
    expect((png.width, png.height, png.components), (2, 2, 3));
    expect(png.samples, [255, 0, 0, 0, 255, 0, 0, 0, 255, 10, 20, 30]);
    expect(png.alpha, [255, 128, 0, 77]);
  });

  test('16-bit grayscale reduces to the high byte', () {
    final png = PngImage.decode(_bytes(_gray16));
    expect((png.width, png.height, png.components), (3, 2, 1));
    expect(png.samples, [0x00, 0x80, 0xFF, 0x11, 0x22, 0x33]);
  });

  test('4-bit palette with tRNS', () {
    final png = PngImage.decode(_bytes(_palette4));
    expect((png.width, png.height, png.components), (4, 2, 3));
    expect(png.samples, [
      255, 0, 0, 0, 255, 0, 0, 0, 255, 255, 0, 0, //
      0, 0, 255, 0, 0, 255, 0, 255, 0, 0, 255, 0,
    ]);
    expect(png.alpha, [255, 128, 0, 255, 0, 0, 128, 128]);
  });

  test('1-bit grayscale packs across byte boundaries', () {
    final png = PngImage.decode(_bytes(_gray1));
    expect((png.width, png.height, png.components), (9, 2, 1));
    int bit(String s, int i) => s[i] == '1' ? 255 : 0;
    expect(png.samples, [
      for (var x = 0; x < 9; x++) bit('101010101', x),
      for (var x = 0; x < 9; x++) bit('110011001', x),
    ]);
  });

  test('Adam7 interlaced RGB', () {
    final png = PngImage.decode(_bytes(_interlaced));
    expect((png.width, png.height, png.components), (9, 9, 3));
    for (var y = 0; y < 9; y++) {
      for (var x = 0; x < 9; x++) {
        final i = (y * 9 + x) * 3;
        expect(png.samples.sublist(i, i + 3), [x * 25, y * 25, (x + y) * 12],
            reason: 'pixel ($x,$y)');
      }
    }
  });

  test('gray + alpha', () {
    final png = PngImage.decode(_bytes(_grayAlpha));
    expect((png.width, png.height, png.components), (2, 2, 1));
    expect(png.samples, [10, 200, 99, 0]);
    expect(png.alpha, [255, 0, 128, 1]);
  });

  test('RGB color-key transparency', () {
    final png = PngImage.decode(_bytes(_colorKey));
    expect((png.width, png.height, png.components), (2, 2, 3));
    expect(png.samples, [255, 0, 0, 0, 255, 0, 0, 255, 0, 9, 9, 9]);
    expect(png.alpha, [255, 0, 0, 255]);
  });

  test('rejects non-PNG bytes', () {
    expect(() => PngImage.decode(Uint8List.fromList([1, 2, 3])),
        throwsArgumentError);
  });

  test('random RGBA round-trips through a filter-0 encoder', () {
    final random = Random(42);
    for (final (w, h) in [(1, 1), (7, 3), (16, 16)]) {
      final raw = Uint8List(w * h * 4);
      for (var i = 0; i < raw.length; i++) {
        raw[i] = random.nextInt(256);
      }
      final png = PngImage.decode(_encodeRgba(w, h, raw));
      expect((png.width, png.height, png.components), (w, h, 3));
      for (var i = 0; i < w * h; i++) {
        expect(png.samples.sublist(i * 3, i * 3 + 3),
            raw.sublist(i * 4, i * 4 + 3));
        expect(png.alpha![i], raw[i * 4 + 3]);
      }
    }
  });
}

/// Minimal PNG encoder (RGBA-8, filter 0) for round-trip fuzzing.
Uint8List _encodeRgba(int width, int height, Uint8List rgba) {
  final raw = BytesBuilder();
  for (var y = 0; y < height; y++) {
    raw.addByte(0);
    raw.add(rgba.sublist(y * width * 4, (y + 1) * width * 4));
  }
  final out = BytesBuilder()
    ..add([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);
  void chunk(String type, List<int> data) {
    final body = [...type.codeUnits, ...data];
    out
      ..add(_be(data.length))
      ..add(body)
      ..add(_be(getCrc32(body)));
  }

  chunk('IHDR', [..._be(width), ..._be(height), 8, 6, 0, 0, 0]);
  chunk('IDAT', const ZLibEncoder().encode(raw.takeBytes()));
  chunk('IEND', const []);
  return out.takeBytes();
}

List<int> _be(int value) =>
    [(value >> 24) & 0xFF, (value >> 16) & 0xFF, (value >> 8) & 0xFF, value & 0xFF];
